# Site
repository: ashdoge.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ashwin Vinod
title: High School Student
email: kikoosachu@gmail.com
website: https://ashdoge.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: ashdoge
github_username:  ashdoge
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: a.v1nod
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: AshDoge
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello. My name is Ashwin Vinod. I am currently a high school student attending Mission San Jose High School. 

  I am most skilled in: <mark>Python</mark> and <mark>Guitar</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: The Empty Candy Bag  
        link: https://www.youtube.com/watch?v=0ox9TkmOzr4
        # link_text: Project Website
        additional_links:
          - title:  Making of The Empty Candy Bag
            icon: fab fa-github
            url: https://www.youtube.com/watch?v=1EPu5CfFkiQ
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest movies ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mission San Jose High School
        caption: 2020 - 2024
        sub_title: High School Diploma
        quote: >
          Mission San Jose High is ranked fifth within California.
        description: | # this will include new lines to allow paragraphs
          During my time at Mission San Jose High School I am learning most of my key skills that have I have taken through my career such as collaborating and perservering. I learnt a lot about a healthy work life balance.
    
      - layout: left
        title: Ohlone College
        caption: 2020 - 2024
        sub_title: College Courses
        quote: >
          On December 7, 1965 Fremont and Newark voters approved the creation of the Fremont Newark Junior College District and elected a seven-member Board of Trustees.  Ohlone College was established to serve the cities of Fremont and Newark.
        description: | # this will include new lines to allow paragraphs
          I am taking courses at Ohlone College concurrently with high school. I have gained an understanding of how college level courses work.
          * Completed Courses
          ** Physics 108

  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rice University
        caption: 2020 
        sub_title: Certificate
        quote: >
          Coursera Inc. is an American massive open online course provider founded in 2012 by Stanford University computer science professors Andrew Ng and Daphne Koller.
        link:
          https://coursera.org/share/4dac553fb7aca5793b8646e356ce2e82
            
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in programming and mathematics are:
      - Guitar
      - Dance
      - Volleyball
      - Singing


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
